package com.example.model;
// Generated Apr 23, 2018 5:43:06 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Name generated by hbm2java
 */
@Entity
@Table(name="brand_name"
    ,catalog="`SPRING-SECURITY-TUTORIAL`"
)
public class BrandName  implements java.io.Serializable {


     private Integer brandId;
     private User user;
     private BrandType brandType;
     private String code;
     private String name;
     private String bandWoner;
     private String brandDesc;
     private Date entryDate;

    public BrandName() {
    }

    public BrandName(User user, BrandType brandType, String code, String name, String bandWoner, String brandDesc, Date entryDate) {
       this.user = user;
       this.brandType = brandType;
       this.code = code;
       this.name = name;
       this.bandWoner = bandWoner;
       this.brandDesc = brandDesc;
       this.entryDate = entryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="brand_id", unique=true, nullable=false)
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entry_user")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_type_id")
    public BrandType getBrandType() {
        return this.brandType;
    }
    
    public void setBrandType(BrandType brandType) {
        this.brandType = brandType;
    }

    
    @Column(name="brand_code", length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="brand_name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="band_woner", length=50)
    public String getBandWoner() {
        return this.bandWoner;
    }
    
    public void setBandWoner(String bandWoner) {
        this.bandWoner = bandWoner;
    }

    
    @Column(name="brand_desc", length=100)
    public String getBrandDesc() {
        return this.brandDesc;
    }
    
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entry_date", length=19)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

}


