package com.example.model;
// Generated Apr 23, 2018 12:41:34 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="`SPRING-SECURITY-TUTORIAL`"
)
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String invoice;
     private Double totalPrice;
     private Integer quantity;
     private Double less;
     private Double vat;
     private Double profit;
     private String phone;
     private String name;
     private String address;
     private Date entryDate;

    public Invoice() {
    }

    public Invoice(User user, String invoice, Double totalPrice, Integer quantity, Double less, Double vat, Double profit, String phone, String name, String address, Date entryDate) {
       this.user = user;
       this.invoice = invoice;
       this.totalPrice = totalPrice;
       this.quantity = quantity;
       this.less = less;
       this.vat = vat;
       this.profit = profit;
       this.phone = phone;
       this.name = name;
       this.address = address;
       this.entryDate = entryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entry_user")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="invoice", length=45)
    public String getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }

    
    @Column(name="total_price", precision=22, scale=0)
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="less", precision=22, scale=0)
    public Double getLess() {
        return this.less;
    }
    
    public void setLess(Double less) {
        this.less = less;
    }

    
    @Column(name="vat", precision=22, scale=0)
    public Double getVat() {
        return this.vat;
    }
    
    public void setVat(Double vat) {
        this.vat = vat;
    }

    
    @Column(name="profit", precision=22, scale=0)
    public Double getProfit() {
        return this.profit;
    }
    
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    
    @Column(name="phone", length=15)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entry_date", length=19)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }


}


