package com.example.model;
// Generated Apr 23, 2018 12:41:34 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * InvoiceDetail generated by hbm2java
 */
@Entity
@Table(name="invoice_detail"
    ,catalog="`SPRING-SECURITY-TUTORIAL`"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class InvoiceDetail  implements java.io.Serializable {


     private Integer id;
     private Store store;
     private Invoice invoice;
     private Double unitPrice;
     private Double salsePrice;
     private Double less;
     private Double vat;
     private Double profit;

    public InvoiceDetail() {
    }

    public InvoiceDetail(Store store, Invoice invoice, Double unitPrice, Double salsePrice, Double less, Double vat, Double profit) {
       this.store = store;
       this.invoice = invoice;
       this.unitPrice = unitPrice;
       this.salsePrice = salsePrice;
       this.less = less;
       this.vat = vat;
       this.profit = profit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="store_id")
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="invocie_id")
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    
    @Column(name="unit_price", precision=22, scale=0)
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="salse_price", precision=22, scale=0)
    public Double getSalsePrice() {
        return this.salsePrice;
    }
    
    public void setSalsePrice(Double salsePrice) {
        this.salsePrice = salsePrice;
    }

    
    @Column(name="less", precision=22, scale=0)
    public Double getLess() {
        return this.less;
    }
    
    public void setLess(Double less) {
        this.less = less;
    }

    
    @Column(name="vat", precision=22, scale=0)
    public Double getVat() {
        return this.vat;
    }
    
    public void setVat(Double vat) {
        this.vat = vat;
    }

    
    @Column(name="profit", precision=22, scale=0)
    public Double getProfit() {
        return this.profit;
    }
    
    public void setProfit(Double profit) {
        this.profit = profit;
    }




}


