package com.example.model;
// Generated Apr 23, 2018 12:41:34 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name="model"
    ,catalog="`SPRING-SECURITY-TUTORIAL`"
)
public class Model  implements java.io.Serializable {


     private int id;
     private User user;
     private BrandName brandName;
     private String code;
     private String name;
     private String description;
     private Date entryDate;

    public Model() {
    }

	
    public Model(int id) {
        this.id = id;
    }
    public Model(int id, User user, BrandName brandName, String code, String name, String description, Date entryDate) {
       this.id = id;
       this.user = user;
       this.brandName = brandName;
       this.code = code;
       this.name = name;
       this.description = description;
       this.entryDate = entryDate;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entry_user")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id")
    public BrandName getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(BrandName brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="code", length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entry_date", length=19)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }




}


