package com.example.model;
// Generated Apr 23, 2018 12:41:34 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wholeseller generated by hbm2java
 */
@Entity
@Table(name="wholeseller"
    ,catalog="`SPRING-SECURITY-TUTORIAL`"
)
public class Wholeseller  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String code;
     private String firstName;
     private String lastName;
     private String contactOne;
     private String contactTwo;
     private String storeName;
     private String products;
     private String description;
     private String email;
     private String postCode;
     private String address;
     private Date entryDate;

    public Wholeseller() {
    }

    public Wholeseller(User user, String code, String firstName, String lastName, String contactOne, String contactTwo, String storeName, String products, String description, String email, String postCode, String address, Date entryDate) {
       this.user = user;
       this.code = code;
       this.firstName = firstName;
       this.lastName = lastName;
       this.contactOne = contactOne;
       this.contactTwo = contactTwo;
       this.storeName = storeName;
       this.products = products;
       this.description = description;
       this.email = email;
       this.postCode = postCode;
       this.address = address;
       this.entryDate = entryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entry_user")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="code", length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="contact_one", length=15)
    public String getContactOne() {
        return this.contactOne;
    }
    
    public void setContactOne(String contactOne) {
        this.contactOne = contactOne;
    }

    
    @Column(name="contact_two", length=15)
    public String getContactTwo() {
        return this.contactTwo;
    }
    
    public void setContactTwo(String contactTwo) {
        this.contactTwo = contactTwo;
    }

    
    @Column(name="store_name", length=50)
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    
    @Column(name="products", length=100)
    public String getProducts() {
        return this.products;
    }
    
    public void setProducts(String products) {
        this.products = products;
    }

    
    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="email", length=25)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="post_code", length=10)
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entry_date", length=19)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

}


